### ISSUE TITLE
segfaults when installing developer version on linux

### ISSUE THREAD

**Issue by gully** [nksaunders/scope#8]
I get segmentation fault when installing scope on Linux in the developer version (`python setup.py develop`):

```python
import scope                                                            
Segmentation fault (core dumped)
```
I recently installed on a mac with no problem.  I suspect the issue could be related to subtle implicit dependencies?  Here is one permutation of the conda environment file I tried.

```yaml
name: scope_test03
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - astropy>=3.1
  - pytest-runner
  - astroquery
  - scipy
  - oktopus
  - bokeh>=1.0
  - ipython
  - pytest
  - scikit-learn
  - requests
  - tqdm
  - george
  - beautifulsoup4
  - pybind11
  - starry
  - celerite
  - pip
  - nose
  - lightkurve
  - pytest-cov
  - pytest-remotedata
  - pip:
      - astroML
      - everest-pipeline
      - pysyzygy
      - fbpca

```
